apiVersion: v1
kind: Secret
metadata:
  namespace: olOic1YXhd
  name: dockerhub
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICJhdXRocyI6ewogICAgImh0dHBzOi8vaW5kZXguZG9ja2VyLmlvL3YxLyI6ewogICAgICAidXNlcm5hbWUiOiIiLAogICAgICAicGFzc3dvcmQiOiIiLAogICAgICAiZW1haWwiOiIiLAogICAgICAiYXV0aCI6Ik9nPT0iCiAgICB9CiAgfQp9Cg==
