apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: release-name-prometheus-new-relic-app-exporter
  labels:
    app.kubernetes.io/name: prometheus-new-relic-app-exporter
    helm.sh/chart: prometheus-new-relic-app-exporter-1.0.0
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: 0.0.2
    app.kubernetes.io/managed-by: Helm
data:
  new_relic_api_key: PGNoYW5nZS1tZT4=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-prometheus-new-relic-app-exporter
  labels:
    app.kubernetes.io/name: prometheus-new-relic-app-exporter
    helm.sh/chart: prometheus-new-relic-app-exporter-1.0.0
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: 0.0.2
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-new-relic-app-exporter
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prometheus-new-relic-app-exporter
        app.kubernetes.io/instance: release-name
      annotations:
        checksum/config-secret: a4aae3337df40b3b5559925f8658ae5b5f901284ca93bd351a0675de9f5e119a
        prometheus.io/path: /metrics
        prometheus.io/port: "9000"
        prometheus.io_scrape: "true"
    spec:
      securityContext: {}
      containers:
        - name: prometheus-new-relic-app-exporter
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: false
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                "": NET_RAW
          image: maxrocketinternet/new-relic-app-exporter:0.1
          imagePullPolicy: IfNotPresent
          env:
            - name: NEW_RELIC_API_KEY
              valueFrom:
                secretKeyRef:
                  name: release-name-prometheus-new-relic-app-exporter
                  key: new_relic_api_key
            - name: NEW_RELIC_APPLICATION
              value: my-app
          livenessProbe:
            failureThreshold: 2
            initialDelaySeconds: 5
            periodSeconds: 30
            tcpSocket:
              port: 9000
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 2
            initialDelaySeconds: 5
            periodSeconds: 30
            tcpSocket:
              port: 9000
            timeoutSeconds: 5
          ports:
            - name: prometheus
              containerPort: 9000
              protocol: TCP
          resources:
            seccompProfile:
              type: RuntimeDefault
