apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-msteams-config
data:
  connectors.yaml: |
    connectors_with_custom_templates:
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-msteams-card-template
binaryData:
  card.tmpl: e3sgZGVmaW5lICJ0ZWFtcy5jYXJkIiB9fQp7CiAgIkB0eXBlIjogIk1lc3NhZ2VDYXJkIiwKICAiQGNvbnRleHQiOiAiaHR0cDovL3NjaGVtYS5vcmcvZXh0ZW5zaW9ucyIsCiAgInRoZW1lQ29sb3IiOiAie3stIGlmIGVxIC5TdGF0dXMgInJlc29sdmVkIiAtfX0yREM3MkQKICAgICAgICAgICAgICAgICB7ey0gZWxzZSBpZiBlcSAuU3RhdHVzICJmaXJpbmciIC19fQogICAgICAgICAgICAgICAgICAgIHt7LSBpZiBlcSAuQ29tbW9uTGFiZWxzLnNldmVyaXR5ICJjcml0aWNhbCIgLX19OEMxQTFBCiAgICAgICAgICAgICAgICAgICAge3stIGVsc2UgaWYgZXEgLkNvbW1vbkxhYmVscy5zZXZlcml0eSAid2FybmluZyIgLX19RkZBNTAwCiAgICAgICAgICAgICAgICAgICAge3stIGVsc2UgLX19ODA4MDgwe3stIGVuZCAtfX0KICAgICAgICAgICAgICAgICB7ey0gZWxzZSAtfX04MDgwODB7ey0gZW5kIC19fSIsCiAgInN1bW1hcnkiOiAie3stIGlmIGVxIC5Db21tb25Bbm5vdGF0aW9ucy5zdW1tYXJ5ICIiIC19fQogICAgICAgICAgICAgICAgICB7ey0gaWYgZXEgLkNvbW1vbkFubm90YXRpb25zLm1lc3NhZ2UgIiIgLX19CiAgICAgICAgICAgICAgICAgICAge3stIGlmIGVxIC5Db21tb25MYWJlbHMuYWxlcnRuYW1lICIiIC19fQogICAgICAgICAgICAgICAgICAgICAgUHJvbWV0aGV1cyBBbGVydAogICAgICAgICAgICAgICAgICAgIHt7LSBlbHNlIC19fQogICAgICAgICAgICAgICAgICAgICAge3stIC5Db21tb25MYWJlbHMuYWxlcnRuYW1lIC19fQogICAgICAgICAgICAgICAgICAgIHt7LSBlbmQgLX19CiAgICAgICAgICAgICAgICAgIHt7LSBlbHNlIC19fQogICAgICAgICAgICAgICAgICAgIHt7LSAuQ29tbW9uQW5ub3RhdGlvbnMubWVzc2FnZSAtfX0KICAgICAgICAgICAgICAgICAge3stIGVuZCAtfX0KICAgICAgICAgICAgICB7ey0gZWxzZSAtfX0KICAgICAgICAgICAgICAgICAge3stIC5Db21tb25Bbm5vdGF0aW9ucy5zdW1tYXJ5IC19fQogICAgICAgICAgICAgIHt7LSBlbmQgLX19IiwKICAidGl0bGUiOiAiUHJvbWV0aGV1cyBBbGVydCAoe3sgLlN0YXR1cyB8IHRpdGxlIH19KSIsCiAgInNlY3Rpb25zIjogWyB7eyRleHRlcm5hbFVybCA6PSAuRXh0ZXJuYWxVUkx9fQogIHt7LSByYW5nZSAkaW5kZXgsICRhbGVydCA6PSAuQWxlcnRzIH19e3stIGlmICRpbmRleCB9fSx7ey0gZW5kIH19CiAgICB7CiAgICAgICJhY3Rpdml0eVRpdGxlIjogIlt7eyAkYWxlcnQuQW5ub3RhdGlvbnMuZGVzY3JpcHRpb24gfX1dKHt7ICRleHRlcm5hbFVybCB9fSkiLAogICAgICAiZmFjdHMiOiBbCiAgICAgICAge3stIHJhbmdlICRrZXksICR2YWx1ZSA6PSAkYWxlcnQuQW5ub3RhdGlvbnMgfX0KICAgICAgICB7CiAgICAgICAgICB7ey0gaWYgbmUgJGtleSAiZGVzY3JpcHRpb24iIC19fQogICAgICAgICAgICAibmFtZSI6ICJ7eyAka2V5IH19IiwKICAgICAgICAgICAgInZhbHVlIjogInt7ICR2YWx1ZSB9fSIKICAgICAgICAgIHt7LSBlbmQgLX19CiAgICAgICAgfSwKICAgICAgICB7ey0gZW5kIC19fQogICAgICAgIHt7JGMgOj0gY291bnRlcn19e3sgcmFuZ2UgJGtleSwgJHZhbHVlIDo9ICRhbGVydC5MYWJlbHMgfX17e2lmIGNhbGwgJGN9fSx7eyBlbmQgfX0KICAgICAgICB7CiAgICAgICAgICAibmFtZSI6ICJ7eyAka2V5IH19IiwKICAgICAgICAgICJ2YWx1ZSI6ICJ7eyAkdmFsdWUgfX0iCiAgICAgICAgfQogICAgICAgIHt7LSBlbmQgfX0KICAgICAgXSwKICAgICAgIm1hcmtkb3duIjogdHJ1ZQogICAgfQogICAge3stIGVuZCB9fQogIF0KfQp7eyBlbmQgfX0K
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-msteams
  labels:
    app: prometheus-msteams
    chart: prometheus-msteams-1.3.0
    release: release-name
    heritage: Helm
spec:
  type: ClusterIP
  ports:
    - port: 2000
      targetPort: http
      protocol: TCP
  selector:
    app: prometheus-msteams
    release: release-name
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-msteams
  labels:
    app: prometheus-msteams
    chart: prometheus-msteams-1.3.0
    release: release-name
    heritage: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-msteams
      release: release-name
  template:
    metadata:
      labels:
        app: prometheus-msteams
        release: release-name
      annotations:
        checksum/config: 5a0c213a81c2bab7811b4b962870deda60b635296d47767ea666c7885e417864
        checksum/msteams-card-templates: 159dd39e0712672ba37bc14f6e24aa99dba9f049a10e13c8f42de11788e74a96
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: prometheus-msteams-config
        - name: card-template-volume
          configMap:
            name: prometheus-msteams-card-template
      containers:
        - name: prometheus-msteams
          image: quay.io/prometheusmsteams/prometheus-msteams:v1.5.0
          imagePullPolicy: Always
          env: null
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
            - name: card-template-volume
              mountPath: /etc/template
          args:
            - -config-file=/etc/config/connectors.yaml
            - -template-file=/etc/template/card.tmpl
          ports:
            - name: http
              containerPort: 2000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /config
              port: http
            initialDelaySeconds: 1
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /config
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            limits:
              cpu: 10m
              memory: 32Mi
            requests:
              cpu: 1m
              memory: 8Mi
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
