apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name-ingress-annotator
  labels:
    app.kubernetes.io/name: ingress-annotator
    helm.sh/chart: ingress-annotator-0.2.0
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: release-name-ingress-annotator
  labels:
    app.kubernetes.io/name: ingress-annotator
    helm.sh/chart: ingress-annotator-0.2.0
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
data:
  config.yaml: 'annotations:'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: release-name-ingress-annotator
  labels:
    app.kubernetes.io/name: ingress-annotator
    helm.sh/chart: ingress-annotator-0.2.0
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
rules:
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
      - update
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: release-name-ingress-annotator
  labels:
    app.kubernetes.io/name: ingress-annotator
    helm.sh/chart: ingress-annotator-0.2.0
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: release-name-ingress-annotator
subjects:
  - kind: ServiceAccount
    name: release-name-ingress-annotator
    namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-ingress-annotator
  labels:
    app.kubernetes.io/name: ingress-annotator
    helm.sh/chart: ingress-annotator-0.2.0
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-annotator
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ingress-annotator
        app.kubernetes.io/instance: release-name
    spec:
      serviceAccountName: release-name-ingress-annotator
      containers:
        - name: ingress-annotator
          image: kiwigrid/ingress-annotator:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: CONFIG_PATH
              value: /etc/config/config.yaml
          volumeMounts:
            - mountPath: /etc/config
              name: config-volume
          resources:
            seccompProfile:
              type: RuntimeDefault
      volumes:
        - configMap:
            name: release-name-ingress-annotator
          name: config-volume
