apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name-ingressauthgenerator-rbac
  namespace: rgL1GyPl7L8ng6
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: release-name-ingressauthgenerator-rbac
subjects:
  - kind: ServiceAccount
    name: release-name-ingressauthgenerator-rbac
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-ingressauthgenerator
  labels:
    app: release-name-ingressauthgenerator
    chart: ingressauthgenerator-0.0.4
    release: release-name
    heritage: Helm
spec:
  replicas: 1
  template:
    metadata:
      labels:
        heritage: Helm
        release: release-name
        app: release-name-ingressauthgenerator
        component: release-name-ingressauthgenerator
    spec:
      serviceAccountName: release-name-ingressauthgenerator-rbac
      containers:
        - name: ingressauthgenerator
          image: banzaicloud/ingressauthgenerator:0.0.2
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 10m
              memory: 120Mi
            seccompProfile:
              type: RuntimeDefault
