apiVersion: v1
kind: ConfigMap
metadata:
  name: release-name-pixiecore-simpleconfig
  labels:
    app: pixiecore-simpleconfig
    chart: pixiecore-simpleconfig-0.1.5
    release: release-name
    heritage: Helm
data: null
---
apiVersion: v1
kind: Service
metadata:
  name: pixiecore
  labels:
    app: pixiecore-simpleconfig
    chart: pixiecore-simpleconfig-0.1.5
    release: release-name
    heritage: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  externalIPs: null
  selector:
    app: pixiecore-simpleconfig
    release: release-name
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-pixiecore-simpleconfig
  labels:
    app: pixiecore-simpleconfig
    chart: pixiecore-simpleconfig-0.1.5
    release: release-name
    heritage: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pixiecore-simpleconfig
      release: release-name
  template:
    metadata:
      labels:
        app: pixiecore-simpleconfig
        release: release-name
      annotations:
        checksum/config: fa846ef313da3b56c27bcfb86176712de6017793024f7d1ecaa90fe47c1b2b75
    spec:
      containers:
        - name: pixiecore-simpleconfig
          image: nginx:stable
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - name: config
              mountPath: /usr/share/nginx/html/v1/boot
      volumes:
        - name: config
          configMap:
            name: release-name-pixiecore-simpleconfig
            items: null
