apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: release-name-prometheus-soti-mobicontrol-exporter
  labels:
    app.kubernetes.io/name: prometheus-soti-mobicontrol-exporter
    helm.sh/chart: prometheus-soti-mobicontrol-exporter-1.0.2
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "0.6"
    app.kubernetes.io/managed-by: Helm
data:
  client_id: PGNoYW5nZS1tZT4=
  client_secret: PGNoYW5nZS1tZT4=
  password: PGNoYW5nZS1tZT4=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-prometheus-soti-mobicontrol-exporter
  labels:
    app.kubernetes.io/name: prometheus-soti-mobicontrol-exporter
    helm.sh/chart: prometheus-soti-mobicontrol-exporter-1.0.2
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "0.6"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-soti-mobicontrol-exporter
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prometheus-soti-mobicontrol-exporter
        app.kubernetes.io/instance: release-name
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "9571"
        prometheus.io_scrape: "true"
    spec:
      securityContext: {}
      containers:
        - name: prometheus-soti-mobicontrol-exporter
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                "": NET_RAW
          image: maxrocketinternet/soti-mobicontrol-exporter:0.6
          imagePullPolicy: IfNotPresent
          env:
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: release-name-prometheus-soti-mobicontrol-exporter
                  key: client_id
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: release-name-prometheus-soti-mobicontrol-exporter
                  key: client_secret
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: release-name-prometheus-soti-mobicontrol-exporter
                  key: password
            - name: USERNAME
              value: <change-me>
            - name: MOBICONTROL_HOST
              value: <change-me>
            - name: LOG_LEVEL
              value: INFO
            - name: API_CONCURRECNY
              value: "50"
            - name: API_PAGE_SIZE
              value: "1000"
          livenessProbe:
            failureThreshold: 2
            httpGet:
              path: /healthz
              port: 9571
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 2
            httpGet:
              path: /healthz
              port: 9571
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 5
          ports:
            - name: prometheus
              containerPort: 9571
              protocol: TCP
          resources:
            seccompProfile:
              type: RuntimeDefault
