apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: release-name-prometheus-consul-exporter
  labels:
    app: prometheus-consul-exporter
    chart: prometheus-consul-exporter-0.5.0
    heritage: Helm
    release: release-name
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: docker/default
    seccomp.security.alpha.kubernetes.io/defaultProfileName: docker/default
    apparmor.security.beta.kubernetes.io/allowedProfileNames: runtime/default
    apparmor.security.beta.kubernetes.io/defaultProfileName: runtime/default
spec:
  privileged: false
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
    - ALL
  volumes:
    - configMap
    - emptyDir
    - projected
    - secret
    - downwardAPI
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  readOnlyRootFilesystem: false
  rule: MustRunAsNonRoot
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name-prometheus-consul-exporter
  labels:
    app: prometheus-consul-exporter
    chart: prometheus-consul-exporter-0.5.0
    release: release-name
    heritage: Helm
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: release-name-prometheus-consul-exporter
  labels:
    app: prometheus-consul-exporter
    chart: prometheus-consul-exporter-0.5.0
    heritage: Helm
    release: release-name
rules:
  - apiGroups:
      - extensions
    resources:
      - podsecuritypolicies
    verbs:
      - use
    resourceNames:
      - release-name-prometheus-consul-exporter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: release-name-prometheus-consul-exporter
  labels:
    app: prometheus-consul-exporter
    chart: prometheus-consul-exporter-0.5.0
    heritage: Helm
    release: release-name
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: release-name-prometheus-consul-exporter
subjects:
  - kind: ServiceAccount
    name: release-name-prometheus-consul-exporter
---
apiVersion: v1
kind: Service
metadata:
  name: release-name-prometheus-consul-exporter
  labels:
    app: prometheus-consul-exporter
    chart: prometheus-consul-exporter-0.5.0
    release: release-name
    heritage: Helm
  annotations: {}
spec:
  type: ClusterIP
  ports:
    - port: 9107
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: prometheus-consul-exporter
    release: release-name
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-prometheus-consul-exporter
  labels:
    app: prometheus-consul-exporter
    chart: prometheus-consul-exporter-0.5.0
    release: release-name
    heritage: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-consul-exporter
      release: release-name
  template:
    metadata:
      labels:
        app: prometheus-consul-exporter
        release: release-name
    spec:
      serviceAccountName: release-name-prometheus-consul-exporter
      containers:
        - name: prometheus-consul-exporter
          image: prom/consul-exporter:v0.4.0
          imagePullPolicy: IfNotPresent
          command:
            - consul_exporter
          args:
            - --consul.server=host:port
          ports:
            - name: http
              containerPort: 9107
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            timeoutSeconds: 10
