apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: release-name-prometheus-cloudflare-exporter
  labels:
    app.kubernetes.io/name: prometheus-cloudflare-exporter
    helm.sh/chart: prometheus-cloudflare-exporter-0.0.1
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: 1.2.0
    app.kubernetes.io/managed-by: Helm
data:
  auth_key: PENoYW5nZSBNRT4=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-prometheus-cloudflare-exporter
  labels:
    app.kubernetes.io/name: prometheus-cloudflare-exporter
    helm.sh/chart: prometheus-cloudflare-exporter-0.0.1
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: 1.2.0
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-cloudflare-exporter
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prometheus-cloudflare-exporter
        app.kubernetes.io/instance: release-name
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "9199"
        prometheus.io_scrape: "true"
    spec:
      securityContext: {}
      containers:
        - name: prometheus-cloudflare-exporter
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                "": NET_RAW
            readOnlyRootFilesystem: true
          image: osig/prometheus-cloudflare-exporter:1.2.0
          imagePullPolicy: IfNotPresent
          env:
            - name: AUTH_KEY
              valueFrom:
                secretKeyRef:
                  name: release-name-prometheus-cloudflare-exporter
                  key: auth_key
            - name: AUTH_EMAIL
              value: Change ME>
            - name: ZONE
              value: <Change ME>
          ports:
            - containerPort: 9199
              protocol: TCP
          resources:
            seccompProfile:
              type: RuntimeDefault
